useGroupedVersion: true

version_info_list_js:
  - value: 4.0.1 (latest)
  - value: 4.x
    child:
    - 4.0.1
    - 4.0.0
  - value: 3.x
    child:
    - 3.3.8
    - 3.3.7
    - 3.3.6
    - 3.3.5
    - 3.3.4
    - 3.3.3
    - 3.3.2
    - 3.3.1
    - 3.3.0
    - 3.2.0
    - 3.1.0
    - 3.0.1
    - 3.0.0
  - value: 2.x
    child:
    - 2.3.5
    - 2.3.2
    - 2.3.1
    - 2.3.0
    - 2.1.4
    - 2.1.3
    - 2.1.0
    - 2.0.0
