# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for main and preview branch
  push:
    branches: 
    - main 
    - preview 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-Main" and "Build-Preview"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a multi-line script
        run: |
          cd /home/ubuntu
          [ -d DCEDocJS ] && rm -rf DCEDocJS
          [ -d camera-enhancer-docs-js ] && rm -rf camera-enhancer-docs-js
          [ -d Docs-Template-Repo ] && rm -rf Docs-Template-Repo
          [ ! -d DCEDocJS ] && mkdir -p DCEDocJS
          git clone --depth 1 https://github.com/dynamsoft-docs/camera-enhancer-docs-js.git camera-enhancer-docs-js
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo
          cp -rfp ./camera-enhancer-docs-js/* ./DCEDocJS/
          cp -rfp ./Docs-Template-Repo/* ./DCEDocJS/
          cd DCEDocJS && bundle exec jekyll build --incremental

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_DYNAMSOFT_LOCAL_SERVER }}
          username: ${{ secrets.FTP_DYNAMSOFT_LOCAL_USER }}
          password: ${{ secrets.FTP_DYNAMSOFT_LOCAL_PASSWORD }}
          port: 21 
          local-dir: /home/ubuntu/DCEDocJS/_site/
          server-dir: /www.dynamsoft.com/camera-enhancer/docs/web/

  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    steps:
#new
    - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DCEDocJSPreview ] && rm -rf DCEDocJSPreview
          [ -d camera-enhancer-docs-js-preview ] && rm -rf camera-enhancer-docs-js-preview
          [ -d Docs-Template-Repo-Preview ] && rm -rf Docs-Template-Repo-Preview
          cd /home/ubuntu

      - name: Build the site
        run: |
          cd /home/ubuntu
          [ ! -d DCEDocJSPreview ] && mkdir -p DCEDocJSPreview
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/camera-enhancer-docs-js.git camera-enhancer-docs-js-preview
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
          cp -rfp ./camera-enhancer-docs-js-preview/* ./DCEDocJSPreview/
          cp -rfp ./Docs-Template-Repo-Preview/* ./DCEDocJSPreview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DCEDocJSPreview/_config.yml
          cd DCEDocJSPreview && bundle exec jekyll build --incremental

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DCEDocJSPreview/_site/
          server-dir: /www.dynamsoft.com/camera-enhancer/docs/web/

          
